export const CATEGORIES = [
  "Phones & Tablets",
  "TV & High Tech",
  "Computers & IT",
  "Electronics",
  "Mobile Accessories",
  "Video Games & Consoles",
  "Appliances",
  "Home, Kitchen & Office",
  "Clothing & Shoes",
  "Men's Clothing",
  "Women's Clothing",
  "Formal Wear",
  "Winter Wear",
  "Kids' Fashion",
  "Baby & Toys",
  "Shoes",
  "Watches",
  "Jewelry",
  "Bags & Backpacks",
  "Fashion Accessories",
  "Sports & Leisure",
  "Sport & Outdoors",
  "Beauty & Health",
  "Supermarket & Grocery",
  "Home & Lifestyle",
  "Gifts"
]